version: 2

updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
      time: "07:00"
    open-pull-requests-limit: 10

  - package-ecosystem: gradle
    directory: "/build-logic/src/main/groovy/"
    schedule:
      interval: daily
      time: "07:00"
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "06:00"
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
      time: "05:00"
    open-pull-requests-limit: 5